[workspace]
authors = ["w32zhong <clock126@126.com>"]
channels = ["conda-forge"]
name = "mlir-study"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.13.7.*"
cmake = ">=4.2.2,<5"
ninja = ">=1.13.2,<2"

[pypi-dependencies]
setuptools = ">=80.10.1, <81"
pyyaml = ">=6.0.3, <7"
pip = ">=25.3, <26"
packaging = ">=26.0, <27"
typing-extensions = ">=4.15.0, <5"
